name: Release App

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'master'
    paths:
      - 'ownd-app/pubspec.yaml'
      - 'ownd-app/config/prod.json'
      - '.github/workflows/release-app.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ownd-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        shell: bash
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | cut -d ' ' -f 2 | cut -d '+' -f 1)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Detected Version: $VERSION"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        shell: bash
        run: |
          API_BASE_URL=$(jq -r '.OWND_API_BASE_URL' config/prod.json)
          flutter build apk --split-per-abi --release --build-number=${{ github.run_number }} --dart-define=OWND_API_BASE_URL="$API_BASE_URL"

      - name: Rename APK
        run: |
          cd build/app/outputs/flutter-apk/
          for file in app-*-release.apk; do
            ABI=$(echo $file | sed 's/app-\(.*\)-release.apk/\1/')
            mv "$file" "ownd_v${{ steps.get_version.outputs.VERSION }}_${ABI}.apk"
          done

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          files: ownd-app/build/app/outputs/flutter-apk/ownd_v*.apk
          generate_release_notes: true
